### ISSUE TITLE
flux-controller: remove limits

### ISSUE THREAD

**Issue by jazzlyn** [tyriis/home-ops#2666]
limits are set
```yaml
Limits:
  cpu:     2 
  memory:  2Gi
```
for helm. kustomize, notification and source controller

remove
